/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation(project(":domain"))

    implementation(project(":domain-implementations:jdbc"))

    implementation(project(":domain-implementations:jpa"))

    implementation("de.vandermeer:asciitable:0.3.2")
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.App"
}
